import { ExerciseDefinition } from '../types';

export const EXERCISE_DATABASE: ExerciseDefinition[] = [
  // --- BODYWEIGHT / NO EQUIPMENT (Home, Gym, Outdoor) ---
  {
    id: 'push-up',
    name: 'Push-up',
    muscleGroups: ['CHEST', 'TRICEPS', 'SHOULDERS', 'CORE'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Keep your core braced and spine neutral. Lower your chest until it touches or hovers just above the floor, then press back up.',
    defaultReps: '10-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-up',
    muscleGroups: ['TRICEPS', 'CHEST'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Form a diamond shape with your hands beneath your chest. Keep elbows tucked close to your ribs as you press.',
    defaultReps: '8-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-up',
    muscleGroups: ['SHOULDERS', 'TRICEPS'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Hinge at the hips with elevated glutes. Lower your head diagonally forward between your hands and push upward.',
    defaultReps: '8-10 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    muscleGroups: ['LEGS'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Feet shoulder-width apart. Drive your hips backward, keep knees tracking over toes, and descend to parallel.',
    defaultReps: '15-20 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    muscleGroups: ['LEGS'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Step forward into a deep lunge, keeping your torso tall. Hover back knee right above floor level and push forward.',
    defaultReps: '12 reps / leg',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    muscleGroups: ['LEGS', 'CORE'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Lie on your back, bend one knee and extend the other leg. Drive through your heel to contract your glute at top.',
    defaultReps: '12-15 reps / side',
    defaultSets: 3,
    restSeconds: 45
  },
  {
    id: 'plank',
    name: 'Plank',
    muscleGroups: ['CORE'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Rest on forearms and toes. Maintain a straight line from your shoulders to your heels with core braced.',
    defaultReps: '45-60 sec',
    defaultSets: 3,
    restSeconds: 45
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    muscleGroups: ['CORE', 'CARDIO'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'From high plank position, drive knees alternately toward your chest in a rapid, controlled cadence.',
    defaultReps: '30-45 sec',
    defaultSets: 3,
    restSeconds: 45
  },
  {
    id: 'inverted-doorframe-row',
    name: 'Doorframe Inverted Row',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: [],
    environments: ['HOME', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Grip a sturdy doorframe or vertical pillar. Lean back with straight arms and pull your chest forward.',
    defaultReps: '12-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'chair-bench-dips',
    name: 'Bodyweight Chair / Bench Dips',
    muscleGroups: ['TRICEPS', 'CHEST'],
    equipmentRequired: [],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Place hands on the edge of a sturdy chair or bench. Lower your hips down while keeping elbows pointed backward.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },

  // --- PULL UP BAR EXERCISES ---
  {
    id: 'pull-up',
    name: 'Pull-up',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['PULL_UP_BAR'],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Overhand grip slightly wider than shoulders. Pull yourself up until your chin clears the bar.',
    defaultReps: '6-10 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'chin-up',
    name: 'Chin-up',
    muscleGroups: ['BICEPS', 'BACK'],
    equipmentRequired: ['PULL_UP_BAR'],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Underhand grip shoulder-width. Drive elbows down and back to lift your chin over the bar.',
    defaultReps: '6-10 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroups: ['CORE'],
    equipmentRequired: ['PULL_UP_BAR'],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Hang from the bar with active shoulders. Raise legs straight up to hip height without swinging.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },

  // --- DUMBBELL EXERCISES ---
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    muscleGroups: ['CHEST', 'TRICEPS', 'SHOULDERS'],
    equipmentRequired: ['DUMBBELL', 'BENCH'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Lie on a flat bench. Press dumbbells directly upward until arms are extended, then lower with control.',
    defaultReps: '8-12 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    muscleGroups: ['CHEST', 'SHOULDERS'],
    equipmentRequired: ['DUMBBELL', 'BENCH'],
    environments: ['HOME', 'GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Set bench to 30 degrees. Press dumbbells up to recruit upper pectoral fibers.',
    defaultReps: '8-10 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'dumbbell-floor-press',
    name: 'Dumbbell Floor Press',
    muscleGroups: ['CHEST', 'TRICEPS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Lie on the floor with knees bent. Press dumbbells up until arms lock out, lowering until triceps touch the floor.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['DUMBBELL', 'BENCH'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Support knee and hand on a bench. Row dumbbell back toward your hip, squeezing your lat at top.',
    defaultReps: '10-12 reps / arm',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'standing-dumbbell-row',
    name: 'Standing Bent-Over Dumbbell Row',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Hinge at the hips with flat back. Pull dumbbells up toward your ribs with elbows driving back.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Seated / Standing Dumbbell Shoulder Press',
    muscleGroups: ['SHOULDERS', 'TRICEPS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Hold dumbbells at ear level with palms forward. Press overhead without arching your lower back.',
    defaultReps: '8-10 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    muscleGroups: ['SHOULDERS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Raise dumbbells laterally to shoulder height with a slight forward lean. Pour out the thumbs slightly.',
    defaultReps: '12-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'dumbbell-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    muscleGroups: ['LEGS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Hold a single dumbbell vertically against your chest. Squat deeply between your knees keeping torso upright.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift (RDL)',
    muscleGroups: ['LEGS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Hinge hips back with a slight knee bend. Lower dumbbells along shins until hamstrings stretch, then snap hips forward.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    muscleGroups: ['BICEPS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Keep elbows pinned to your ribs. Curl weights up while supinating wrists at top.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'dumbbell-overhead-tricep-extension',
    name: 'Overhead Dumbbell Tricep Extension',
    muscleGroups: ['TRICEPS'],
    equipmentRequired: ['DUMBBELL'],
    environments: ['HOME', 'GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Hold dumbbell overhead with both hands. Lower behind your neck by bending elbows, then press back up.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },

  // --- BARBELL EXERCISES ---
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    muscleGroups: ['CHEST', 'TRICEPS', 'SHOULDERS'],
    equipmentRequired: ['BARBELL', 'BENCH'],
    environments: ['GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Unrack barbell with shoulder-width grip. Lower to mid-chest with elbows tucked 45 degrees, then press up.',
    defaultReps: '6-8 reps',
    defaultSets: 4,
    restSeconds: 120
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    muscleGroups: ['LEGS', 'CORE'],
    equipmentRequired: ['BARBELL', 'SQUAT_RACK'],
    environments: ['GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Bar resting across upper traps. Break at hips and knees together, descend below parallel, and drive up.',
    defaultReps: '5-8 reps',
    defaultSets: 4,
    restSeconds: 120
  },
  {
    id: 'barbell-deadlift',
    name: 'Conventional Barbell Deadlift',
    muscleGroups: ['BACK', 'LEGS', 'CORE'],
    equipmentRequired: ['BARBELL'],
    environments: ['GYM'],
    difficulty: 'ADVANCED',
    instructions: 'Bar over midfoot. Grip bar, wedge shins, pull slack out of the bar, and drive through the floor to lock out.',
    defaultReps: '5 reps',
    defaultSets: 3,
    restSeconds: 150
  },
  {
    id: 'barbell-overhead-press',
    name: 'Standing Barbell Overhead Press (OHP)',
    muscleGroups: ['SHOULDERS', 'TRICEPS', 'CORE'],
    equipmentRequired: ['BARBELL'],
    environments: ['GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Bar racked on anterior deltoids. Squeeze glutes and press vertically in a straight bar path.',
    defaultReps: '6-8 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['BARBELL'],
    environments: ['GYM'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Torso hinged at 45 degrees. Pull bar into lower ribcage leading with elbows.',
    defaultReps: '8-10 reps',
    defaultSets: 3,
    restSeconds: 90
  },

  // --- CABLE & GYM MACHINES ---
  {
    id: 'cable-lat-pulldown',
    name: 'Cable Lat Pulldown',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['CABLE_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Grip wide bar. Pull down to upper clavicle while depressing scapulae down and back.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'cable-seated-row',
    name: 'Cable Seated Row',
    muscleGroups: ['BACK', 'BICEPS'],
    equipmentRequired: ['CABLE_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Sit tall with chest up. Row cable handle to navel without leaning back excessively.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 75
  },
  {
    id: 'cable-tricep-pushdown',
    name: 'Cable Tricep Pushdown',
    muscleGroups: ['TRICEPS'],
    equipmentRequired: ['CABLE_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Elbows pinned to sides. Extend forearms downward using rope or V-bar, spreading at bottom.',
    defaultReps: '12-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'cable-chest-fly',
    name: 'Cable Chest Fly',
    muscleGroups: ['CHEST'],
    equipmentRequired: ['CABLE_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Step forward from cable towers. Bring hands together in an arc as if hugging a barrel.',
    defaultReps: '12-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'leg-press',
    name: 'Leg Press Machine',
    muscleGroups: ['LEGS'],
    equipmentRequired: ['GYM_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Feet shoulder-width on sled. Lower platform under control to 90 degrees knee bend, then press without locking knees.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 90
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension Machine',
    muscleGroups: ['LEGS'],
    equipmentRequired: ['GYM_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Sit against back pad. Extend knees to lift pad, holding peak contraction for 1 second.',
    defaultReps: '12-15 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Hamstring Leg Curl',
    muscleGroups: ['LEGS'],
    equipmentRequired: ['GYM_MACHINE'],
    environments: ['GYM'],
    difficulty: 'BEGINNER',
    instructions: 'Lie prone with pad against Achilles. Curl heels up toward glutes and lower slowly.',
    defaultReps: '10-12 reps',
    defaultSets: 3,
    restSeconds: 60
  },

  // --- KETTLEBELL & BANDS ---
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    muscleGroups: ['LEGS', 'CORE', 'CARDIO'],
    equipmentRequired: ['KETTLEBELL'],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'INTERMEDIATE',
    instructions: 'Hinge hips back and explosively snap hips forward to float kettlebell to chest height.',
    defaultReps: '15-20 reps',
    defaultSets: 3,
    restSeconds: 60
  },
  {
    id: 'resistance-band-pull-apart',
    name: 'Resistance Band Pull-Apart',
    muscleGroups: ['SHOULDERS', 'BACK'],
    equipmentRequired: ['RESISTANCE_BANDS'],
    environments: ['HOME', 'GYM', 'OUTDOOR'],
    difficulty: 'BEGINNER',
    instructions: 'Hold band in front at shoulder height. Pull arms outward horizontally until band touches chest.',
    defaultReps: '15-20 reps',
    defaultSets: 3,
    restSeconds: 45
  }
];
